---
abstract: 'RT Integration-VersionControl Extension'
author:
  - 'Thomas Sibley <trs@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Integration-VersionControl
no_index:
  directory:
    - html
    - inc
version: 0.90-TRIAL
