name: RT-Integration-SVN
version: 0.01_01
abstract: RT Integration-SVN Extension
author: Jesse Vincent <jesse@bestpractical.com>
license: GPLv2
distribution_type: module
build_requires:
  Module::Install::RTx: 0
no_index:
  directory:
    - html
    - inc
generated_by: Module::Install version 0.33
